version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://vlados:123@db:5432/voting_app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: vlados
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: voting_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vlados -d voting_app"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
